/**
 * @file schema.ts
 * @description Defines the database schema for Convex.
 * Contains tables for access control, study sessions, documents, and AI analytics.
 */

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/** Validator for a single quiz question generated by the AI. */
const quizQuestionValidator = v.object({
  id: v.string(),
  topic: v.string(),
  prompt: v.string(),
  idealAnswer: v.string(),
  explanationHint: v.string(),
});

/** Validator for detailed insights regarding a specific topic. */
const topicInsightValidator = v.object({
  topic: v.string(),
  comfortScore: v.number(), // Value from 0-100
  rationale: v.string(),    // Reasoning for the score
  recommendation: v.string(), // Recommended action
});

/** Validator for the overall result of a learning progress analysis. */
const analysisValidator = v.object({
  overallReadiness: v.number(),
  strongestTopics: v.array(v.string()),
  weakestTopics: v.array(v.string()),
  topics: v.array(topicInsightValidator),
  recommendedNextStep: v.string(),
});

export default defineSchema({
  /** One-time access codes (e.g., for demos or limited-time access) */
  accessCodes: defineTable({
    code: v.string(),
    normalizedCode: v.string(), // Uppercase code for easy lookup
    createdAt: v.number(),
    consumedAt: v.optional(v.number()),
    consumedByGrantId: v.optional(v.id("accessGrants")),
    note: v.optional(v.string()),
  }).index("by_normalizedCode", ["normalizedCode"]),

  /** Active access grants (tokens) assigned to a browser session */
  accessGrants: defineTable({
    token: v.string(),
    accessCodeId: v.id("accessCodes"),
    createdAt: v.number(),
    expiresAt: v.number(),
    revokedAt: v.optional(v.number()),
  })
    .index("by_token", ["token"])
    .index("by_expiresAt", ["expiresAt"]),

  /** A study session containing multiple documents and quiz rounds */
  studySessions: defineTable({
    grantId: v.id("accessGrants"),
    title: v.string(),
    stage: v.union(v.literal("upload"), v.literal("quiz"), v.literal("analysis")),
    round: v.number(), // Counter for the current practice round
    currentFocusTopic: v.optional(v.string()),
    sourceSummary: v.optional(v.string()), // AI summary of all sources
    sourceTopics: v.array(v.string()),    // All topics identified in the sources
    quizQuestions: v.array(quizQuestionValidator),
    analysis: v.optional(analysisValidator), // AI analysis of learning progress
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_grantId", ["grantId"]),

  /** Documents added to a session (PDFs, texts, etc.) */
  sessionDocuments: defineTable({
    sessionId: v.id("studySessions"),
    storageId: v.id("_storage"), // Reference to Convex File Storage
    fileName: v.string(),
    fileType: v.string(),
    fileSizeBytes: v.number(),
    extractionStatus: v.union(
      v.literal("pending"),
      v.literal("processing"),
      v.literal("ready"),
      v.literal("failed"),
    ),
    extractedText: v.optional(v.string()), // Text content extracted by AI
    extractionError: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_sessionId", ["sessionId"])
    .index("by_createdAt", ["createdAt"]),

  /** User responses to generated quiz questions */
  quizResponses: defineTable({
    sessionId: v.id("studySessions"),
    round: v.number(),
    questionId: v.string(),
    topic: v.string(),
    prompt: v.string(),
    userAnswer: v.string(),
    isCorrect: v.boolean(),
    score: v.number(), // Granular evaluation (0.0 to 1.0)
    explanation: v.string(),
    idealAnswer: v.string(),
    timeSpentSeconds: v.number(), // Time taken to answer
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_session_round", ["sessionId", "round"])
    .index("by_session_round_question", ["sessionId", "round", "questionId"])
    .index("by_createdAt", ["createdAt"]),

  /** Observability data for AI operations (tracing, token usage, latency) */
  aiAnalyticsEvents: defineTable({
    traceId: v.string(),
    sessionId: v.id("studySessions"),
    scope: v.string(), // e.g., "quiz_generation", "answer_evaluation"
    status: v.union(v.literal("success"), v.literal("error")),
    privacyMode: v.union(v.literal("balanced"), v.literal("full"), v.literal("off")),
    contentCaptured: v.boolean(),
    telemetryProvider: v.union(v.literal("langfuse"), v.literal("none")),
    modelId: v.optional(v.string()),
    fallbackUsed: v.optional(v.boolean()),
    llmAttempts: v.optional(v.number()),
    latencyMs: v.number(),
    inputTokens: v.optional(v.number()),
    outputTokens: v.optional(v.number()),
    totalTokens: v.optional(v.number()),
    promptTokenCount: v.optional(v.number()),
    candidatesTokenCount: v.optional(v.number()),
    thoughtsTokenCount: v.optional(v.number()),
    documentPromptTokens: v.optional(v.number()),
    textPromptTokens: v.optional(v.number()),
    finishReason: v.optional(v.string()),
    totalDocuments: v.optional(v.number()),
    readyDocuments: v.optional(v.number()),
    filePartCount: v.optional(v.number()),
    sourceContextLength: v.optional(v.number()),
    outputQuestionCount: v.optional(v.number()),
    errorName: v.optional(v.string()),
    errorMessage: v.optional(v.string()),
    errorStackPreview: v.optional(v.string()),
    metadataJson: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_session_createdAt", ["sessionId", "createdAt"])
    .index("by_createdAt", ["createdAt"])
    .index("by_traceId", ["traceId"])
    .index("by_scope_createdAt", ["scope", "createdAt"])
    .index("by_status_createdAt", ["status", "createdAt"]),
});
